### ISSUE TITLE
Callback API?

### ISSUE THREAD

**Issue by baszero** [mebjas/image-jigsaw#2]
Hi,
beautiful jquery library, congratulations! 
Is there an easy way of attaching a listener to each of the generated tile/cell ? e.g. I'd like to create some interaction after the image has been randomly split apart...

**Comment by mebjas** [comment]
Yeah we can definitely add some, what kind of events are you looking for ?

**Comment by baszero** [comment]
I was initially looking for a simple click event.
But as your lib generates a div per cell, I could also attach an event
listener to those DIVs, would that be something solid?

**Comment by mebjas** [comment]
https://github.com/mebjas/image-jigsaw/commit/2e34bb1acb3b2765de91fc48aa5a154827e76357 added the option.
How to use it, 

``` js
$(".panel").jigsaw({freq: 2000, x: 4, y:4, margin: 2, callbacks: [{  
        event: 'mouseover',
        func: function() {
        $(this).data('last_bg', $(this).css('background-image'));
        $(this).css('background-image', 'none');
    }
    }, {
        event: 'mouseout',
        func: function() {
        $(this).css('background-image', $(this).data('last_bg'));
    }
    }
]});
```

add a property `callbacks` which is an array of objects with this structure

``` js
{
event: <event name, ex: click>,
func: <function defination>
}
```

**Comment by baszero** [comment]
Cool! THanks

**Comment by mebjas** [comment]
Thanks for the suggestion!!
