### ISSUE TITLE
JQuery 1.11 Support?

### ISSUE THREAD

**Issue by smulholland2** [mebjas/image-jigsaw#3]
I'm trying to use this in a Wordpress site using JQuery 1.11.3.

I can get it to work fine with JQuery 1.8, but with JQuery 1.11.3 in jquery.image-jigsaw.js on line 59, I get a null object error on obj.

**Comment by mebjas** [comment]
@smulholland2 thanks for reporting the bug, I have attempted to fix it with https://github.com/mebjas/image-jigsaw/commit/be8738ed34e4e8ceffef25a8b0727555c0517275.

Have a look at latest code in repo once. :)

**Comment by mebjas** [comment]
Marking this as fixed.
